import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "../components/header";
import { Footer } from "@/components/footer";

const mainFont = Open_Sans({
  weight: ['300', '400', '700'],
   subsets: ["latin"], 
   variable: '--font-main'
  });

export const metadata: Metadata = {
  title: "E-COMMERCE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mainFont.className}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
